<?php

namespace Arnm\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    /**
     * Find all the media entries with a given tag.
     * This function joins the media entities with the attributes
     *
     * @return array
     */
    public function findAllMediaByTag($slidesTag)
    {
        $query = $this->createQueryBuilder('m')->leftJoin('m.attributes', 'a')
                    ->where('m.tag = :tag')
                    ->setParameter('tag', $slidesTag)
                    ->getQuery();

        return $query->getResult();
    }
}